[package]
name = "rurl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket="5.0"
serde_json="1.0"

[dependencies.rocket_db_pools]
version="0.1.0"
features=["sqlx_sqlite"]
